ha <- read.csv("new_power_consumption.txt")
mydata <- ha
mydata[, "Global_active_power"] <- as.numeric(mydata[, "Global_active_power"])
Sys.setlocale("LC_TIME", "en_US")

full_time <- paste(mydata$Date, as.character(mydata$Time), sep = "-")
mydata$Full_time <- strptime(full_time, "%Y-%m-%d-%H:%M:%S")
mydata$Global_active_power <- as.numeric(mydata$Global_active_power)
mydata$Global_reactive_power <- as.numeric(mydata$Global_reactive_power)
mydata$Sub_metering_1 <- as.numeric(mydata$Sub_metering_1)
mydata$Sub_metering_2 <- as.numeric(mydata$Sub_metering_2)
mydata$Sub_metering_3 <- as.numeric(mydata$Sub_metering_3)
par(mfrow = c(2,2), mar = c(4,4,2,1), oma = c(0,0,2,0))
with(mydata, {
  plot(Full_time, Global_active_power, ylab = "Global Active Power", type = "l", xlab = "")
  plot(Full_time, Voltage, ylab = "Voltage", xlab = "datetime", type="l")
  plot(Full_time, Sub_metering_1, type="l", col="black", ylab = "Energy sub metering")
  lines(Full_time, Sub_metering_2, col="red")
  lines(Full_time, Sub_metering_3, col="blue")
  legend("topright",col=c("black", "red", "blue"), bty="n",legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty='solid')
  plot(Full_time, Global_reactive_power, ylab = "Global_reactive_power", type="l")
  })
dev.copy(png,"plot4.png")
dev.off()